name: JoinOpt
version: '${version}'
main: org.opttools.JoinOpt
api-version: '1.17'
authors: [DApples]
description: About A perfermance plugin for edit minecraft join/exit messages with actions and welcome rewards.
